### ISSUE TITLE
project desktop version of portiflio

### ISSUE THREAD

**Issue by beteland123** [jicamargo/first-mobile-portfolio#6]
complete the desktop version of the home page
nice work on making the home page resonsive

**Comment by BenMKT** [comment]
-Make sure your portfolio desktop version matches the Figma design

**Comment by jicamargo** [comment]
Thanks @beteland123 and @BenMKT for your feedback.

I'm working on this issue, and hope to present the whole desktop version today.

**Comment by Xecyc** [comment]
Good work so far. I would recommend using grid for the other projects section.

**Comment by jicamargo** [comment]
Thanks for your suggestions. All are done.
