### ISSUE TITLE
stand up morning session 2

### ISSUE THREAD

**Issue by jicamargo** [jicamargo/first-mobile-portfolio#9]
# deployment

This project was deployed.

[check it here  ➡️](https://jicamargo.github.io/first-mobile-portfolio/)

Thnaks for any suggestion

**Comment by baezluise** [comment]
Great animations.
Accesibility for buttons is already implemented. Very well!!!. 
Nothing to add. 🥇

**Comment by JuanDBta** [comment]
Hey Jorge, great job! It looks like you put an enormous effort into this project...If I may say something about you could try other kinds of animations to give to your web more interaction and get your end user emotions...So you can try this animation   
   
 animation-duration: 3s;
  animation-name: slidein;
}

@keyframes slidein {
  from {
    margin-left: 100%;
    width: 300%;
  }

  to {
    margin-left: 0%;
    width: 100%;
  }
}
 and give movement to the text in your intro...good luck with your everything!

**Comment by jicamargo** [comment]
Thank you @baezluise and @JuanDBta for your contributions to this project.
I'll take it into account.

**Comment by jicamargo** [comment]
thanks for your suggestions. All Done!
